---
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'bops-applicants/**/*'
    - 'config/environments/**'
    - 'config/puma.rb'

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# be a bit kinder with our metrics
Metrics:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Max: 100
  Exclude:
    - spec/**/*
    - config/routes.rb

Layout/LineLength:
  AllowedPatterns: ['^\s*#']
  Exclude:
    - spec/**/*

Naming/VariableNumber:
  Exclude:
    - db/migrate/*
    - spec/**/*

# we tend to use update_all in migrations
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb

  AllowedMethods:
    - touch

# allow ActiveRecord::Base as a parent class in migrations
Rails/ApplicationRecord:
  Exclude:
    - db/migrate/*.rb

# Rspec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - as
    - before
    - when
    - with
    - without

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

# these two are ignored because they're migrations from the past and we
# don't expect to go back and edit them ever
Rails/BulkChangeTable:
  Exclude:
    - db/migrate/2020*
    - db/migrate/2021*
    - db/migrate/2022*

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/2020*
    - db/migrate/2021*
    - db/migrate/2022*
