inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "db/migrate/*"

RSpec/ContextWording:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
