inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "**/*.gemspec"
    - "node_modules/**/*"
