---
require:
  - standard
  - standard-custom
  - standard-performance
  - standard-rails
  - rubocop-performance
  - rubocop-rails
  - ./lib/bops/cop.rb

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'bops-applicants/**/*'
    - 'db/schema.rb'
    - 'config/environments/**'
    - 'config/puma.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'engines/*/bin/*'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/HaveCurrentPathLiteral:
  Enabled: true
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
  IgnoreHelpers: []

Style/VisitLiteral:
  Enabled: true
  Exclude:
    - 'app/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
  IgnoreHelpers:
    - current_path

# past migrations are ignored; we don't expect to go back and edit them ever,
# we'll fix them in future migrations if at all.
Rails/BulkChangeTable:
  Exclude:
    - db/migrate/202[0123]*

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/202[0123]*

Rails/ReversibleMigrationMethodDefinition:
  Exclude:
    - db/migrate/202[0123]*

Rails/ThreeStateBooleanColumn:
  Exclude:
    - db/migrate/202[012]*
    - db/migrate/20230*
    - db/migrate/202310*

# False positive: if being used in migrations, behaviour is different and intentional
Rails/ApplicationRecord:
  Exclude:
    - db/migrate/*
