---
inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - 'bops-applicants/**/*'
    - 'config/environments/**'
    - 'config/puma.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# be a bit kinder with our metrics
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  Exclude:
    - spec/**/*
    - config/routes.rb

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['^\s*#']
  Exclude:
    - spec/**/*

Naming/VariableNumber:
  Exclude:
    - spec/**/*

# we tend to use update_all in migrations
Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/*.rb

# Rspec
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - as
    - before
    - when
    - with
    - without

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb
