---
services:
  db:
    image: bops/postgis
    build: docker/postgis
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7.0
    command: redis-server
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - type: volume
        source: redis
        target: /var/lib/redis/data

  web:
    image: bops/ruby
    build: docker/ruby
    working_dir: /home/rails/bops
    command: ["bin/dev"]
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
      APPLICANTS_APP_HOST: southwark.bops-applicants.localhost:3001
      GROVER_NO_SANDBOX: "true"
      PIDFILE: /tmp/pids/server.pid
      OS_VECTOR_TILES_API_KEY: ${OS_VECTOR_TILES_API_KEY}
      REDIS_URL: redis://redis:6379/1
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
    networks:
      default:
        aliases:
          - southwark.bops.localhost
    volumes:
      - type: bind
        source: .
        target: /home/rails/bops
      - type: volume
        source: bundle
        target: /home/rails/bundle
      - type: volume
        source: node_modules
        target: /home/rails/bops/node_modules
      - type: tmpfs
        target: /tmp/pids

  applicants:
    image: bops/applicants
    build: bops-applicants/docker/ruby
    working_dir: /home/rails/bops-applicants
    command: ["bin/dev"]
    stdin_open: true
    tty: true
    environment:
      API_BEARER: 123
      API_HOST: southwark.bops.localhost:3000
      API_USER: api_user
      PIDFILE: /tmp/pids/server.pid
      PORT: 3001
      PROTOCOL: http
      OS_VECTOR_TILES_API_KEY: ${OS_VECTOR_TILES_API_KEY}
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      default:
        aliases:
          - southwark.bops-applicants.localhost
    volumes:
      - type: bind
        source: bops-applicants
        target: /home/rails/bops-applicants
      - type: volume
        source: applicants_bundle
        target: /home/rails/bundle
      - type: volume
        source: applicants_node_modules
        target: /home/rails/bops-applicants/node_modules
      - type: tmpfs
        target: /tmp/pids

networks:
  default:
    ipam:
      config:
        - subnet: 172.23.0.0/16
          ip_range: 172.23.9.0/24
          gateway: 172.23.9.254

volumes:
  redis:
  db:
  bundle:
  node_modules:
  applicants_bundle:
  applicants_node_modules:
