---
services:
  db:
    image: postgres:13.4
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: redis
        target: /var/lib/redis/data

  sidekiq:
    depends_on:
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgres://postgres:postgres@db:5432

  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: bash -c "bundle exec bin/dev"
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
      APPLICANTS_APP_HOST: southwark.localhost:3001
      GROVER_NO_SANDBOX: "true"
      OS_VECTOR_TILES_API_KEY: ${OS_VECTOR_TILES_API_KEY}
      REDIS_URL: redis://redis:6379/1
    ports:
      - "3000:3000"
      - "3333:3333"
    depends_on:
      - db
      - sidekiq
      - redis
    networks:
      default:
        aliases:
          - southwark.southwark.localhost
    volumes:
      - type: bind
        source: .
        target: /app
  applicants:
    build: ./bops-applicants
    entrypoint: ./docker-entrypoint.sh
    stdin_open: true
    tty: true
    command: bash -c "bundle exec bin/dev"
    depends_on:
      - web
    environment:
      API_BEARER: 123
      API_HOST: southwark.localhost:3000
      API_USER: api_user
      PORT: 3001
      PROTOCOL: http
      OS_VECTOR_TILES_API_KEY: ${OS_VECTOR_TILES_API_KEY}
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./bops-applicants/
        target: /app

volumes:
  redis:
  db:
