---
services:
  db:
    image: postgres:13.4
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432
      APPLICANTS_APP_HOST: southwark.localhost:3001
      GROVER_NO_SANDBOX: "true"
      OS_VECTOR_TILES_API_KEY: ${OS_VECTOR_TILES_API_KEY}
    ports:
      - "3000:3000"
      - "3333:3333"
    depends_on:
      - db
    networks:
      default:
        aliases:
          - southwark.southwark.localhost
    volumes:
      - type: bind
        source: .
        target: /app
  applicants:
    build: ./bops-applicants
    entrypoint: ./docker-entrypoint.sh
    stdin_open: true
    tty: true
    command: bash -c "bundle exec rails s -p 3001 -b 0.0.0.0"
    environment:
      API_BEARER: 123
      API_HOST: southwark.localhost:3000
      API_USER: api_user
      PORT: 3001
      PROTOCOL: http
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./bops-applicants/
        target: /app

volumes:
  db:
