---
openapi: 3.0.1
info:
  title: Back-office Planning System
  version: v2
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    unauthorized:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              const: 401
            message:
              type: string
              const: Unauthorized
          required:
          - code
          - message
      required:
      - error
    healthcheck:
      type: object
      properties:
        message:
          type: string
          const: OK
        timestamp:
          type: string
          format: date-time
      required:
      - message
      - timestamp
paths:
  "/api/v2/ping":
    get:
      summary: Returns a healthcheck
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Returns a healthcheck
          content:
            application/json:
              examples:
                default:
                  value:
                    message: OK
                    timestamp: '2023-11-22T20:00:00.000Z'
              schema:
                "$ref": "#/components/schemas/healthcheck"
        '401':
          description: Missing or invalid credentials
          content:
            application/json:
              examples:
                default:
                  value:
                    error:
                      code: 401
                      message: Unauthorized
              schema:
                "$ref": "#/components/schemas/unauthorized"
