business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 5:00 pm
  holidays:
    - December 27th, 2021
    - December 28th, 2021
    - Jan 03, 2022
    - April 15th, 2022
    - April 18th, 2022
    - May 02, 2022
    - June 02, 2022
    - June 03, 2022
    - August 29th, 2022
    - December 26th, 2022
    - December 27th, 2022
    - Jan 01, 2023
    - Jan 02, 2023
    - April 07, 2023
    - April 10th, 2023
    - May 01, 2023
    - May 29th, 2023
    - August 28th, 2023
    - December 25th, 2023
    - December 26th, 2023
    - Jan 01, 2024
    - March 29, 2024
    - April 1, 2024
    - May 6, 2024
    - May 27, 2024
    - August 26, 2024
    - December 25, 2024
    - December 26, 2024
    - January 1, 2025
    - April 18, 2025
    - April 21, 2025
    - May 5, 2025
    - May 26, 2025
    - August 25, 2025
    - December 25, 2025
    - December 26, 2025
    - January 1, 2026
    - April 3, 2026
    - April 6, 2026
    - May 4, 2026
    - May 25, 2026
    - August 31, 2026
    - December 25, 2026
    - December 28, 2026
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
