default: &default
  adapter: postgis
  encoding: unicode
  url: <%= ENV.fetch("DATABASE_URL") { "postgis://postgres@localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bops_development

test:
  <<: *default
  database: bops_test

production:
  <<: *default
  database: bops_production
