- name: "Check breach report"
  section: "Check"
  tasks:
    - name: "Check report details"
      tasks:
        - name: "Check description"
          optional: true

    - name: "Check site location"
    - name: "Review constraints"
    - name: "Review site history"
    - name: "Review documents"
    - name: "Start investigation"

- name: "Investigate and decide"
  section: "Investigate"
  tasks:
    - name: "Update site and owner details"
      tasks:
        - name: "Update site location"
        - name: "Add site owners and interested parties"
        - name: "Review site history"
        - name: "Review constraints"

    - name: "Investigation actions"
      tasks:
        - name: "Add investigation action"
        - name: "Add site visit"

    - name: "Assess"
      tasks:
        - name: "Add legislation for assessment"
        - name: "Assess against policy"

    - name: "Summarise and decide"
      tasks:
        - name: "Summarise investigation and make recommendation"
        - name: "Create enforcement notice"
        - name: "Submit recommendation"

- name: "Review recommendation"
  section: "Review"

- name: "Serve notice and monitor compliance"
  section: "Serve and monitor"
  tasks:
    - name: "Serve notice"
      tasks:
        - name: "Add evidence of serving a notice"

    - name: "Required actions"

- name: "Process an appeal"
  section: "Appeal"
