- name: "Check and validate"
  section: "Validation"
- name: "Consultees"
  section: "Consultation"
- name: "Check and assess"
  section: "Assessment"
- name: "View recommendation"
  section: "Review"
