---
name: CI

on: [push, pull_request]

jobs:
  test:
    name: Setup and Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby 2.6.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install JS deps
        run: yarn install

      - name: Install file previewing tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript poppler-utils

      - name: Bundle audit
        run: bundle exec bundle-audit

      - name: Setup database
        shell: bash
        run: bundle exec rake db:setup

      - name: Brakeman
        run: bundle exec brakeman

      - name: Rubocop
        run: bundle exec rubocop

      - name: RSpec
        run: bundle exec rspec

      - name: Cucumber
        run: bundle exec cucumber

  deploy-staging:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy to staging
    runs-on: ubuntu-latest
    environment: staging
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - run: echo "Deploying to staging on branch $GITHUB_REF"

      - name: Deploy staging application
        run: |
          bundle exec rake deploy:preview

  deploy-production:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: [test, deploy-staging]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4

      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - run: echo "Deploying to production on branch $GITHUB_REF"

      - name: Deploy production application
        run: |
          bundle exec rake deploy:production
