---
name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  brakeman:
    uses: ./.github/workflows/linters.yml
    with:
      brakeman: true

  bundle-audit:
    uses: ./.github/workflows/linters.yml
    with:
      bundler-audit: true

  rubocop:
    uses: ./.github/workflows/linters.yml
    with:
      rubocop: true

  specs:
    uses: ./.github/workflows/testing.yml
    strategy:
      matrix:
        specs:
          - ["models", "[a-p]*_spec.rb"]
          - ["models", "[q-z]*_spec.rb"]
          - ["controllers", "*_spec.rb"]
          - ["requests", "*_spec.rb"]
          - ["system", "a[a-s]*_spec.rb"]
          - ["system", "a[t-z]*_spec.rb"]
          - ["system", "[b-f]*_spec.rb"]
          - ["system", "[g-k]*_spec.rb"]
          - ["system", "[l-r]*_spec.rb"]
          - ["system", "[s-z]*_spec.rb"]
          - [
              "other",
              "*_spec.rb",
              "{components,helpers,presenters,mailer,jobs,services,translations}",
            ]
    with:
      name: "${{matrix.specs[0]}}: ${{matrix.specs[1]}}"
      include: "spec/${{matrix.specs[2] || matrix.specs[0]}}/**/${{matrix.specs[1]}}"
    secrets: inherit

  cucumber:
    uses: ./.github/workflows/testing.yml
    with:
      name: "all"
      test-runner: "cucumber"
    secrets: inherit
