---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle-audit:
    uses: ./.github/workflows/linters.yml
    with:
      bundler-audit: true

  brakeman:
    uses: ./.github/workflows/linters.yml
    with:
      brakeman: true

  rubocop:
    uses: ./.github/workflows/linters.yml
    with:
      rubocop: true

  rome:
    uses: ./.github/workflows/linters.yml
    with:
      rome: true

  language-versions:
    uses: ./.github/workflows/linters.yml
    with:
      language-versions: true

  specs:
    uses: ./.github/workflows/testing.yml
    strategy:
      matrix:
        specs:
          - { group: "models", pattern: "[a-p]*_spec.rb" }
          - { group: "models", pattern: "[q-z]*_spec.rb" }
          - { group: "controllers", pattern: "*_spec.rb" }
          - { group: "requests", pattern: "*_spec.rb" }
          - { group: "system", pattern: "a[a-s]*_spec.rb", want_pdf: true }
          - { group: "system", pattern: "a[t-z]*_spec.rb" }
          - { group: "system", pattern: "[b-f]*_spec.rb", want_pdf: true }
          - { group: "system", pattern: "[g-k]*_spec.rb" }
          - { group: "system", pattern: "[l-r]*_spec.rb" }
          - { group: "system", pattern: "[s-z]*_spec.rb" }
          - {
              group: "other",
              pattern: "*_spec.rb",
              directories: "{components,form_models,helpers,presenters,mailer,jobs,services,translations}",
            }
      fail-fast: false
    with:
      name: "${{matrix.specs.group}}: ${{matrix.specs.pattern }}"
      include: "spec/${{matrix.specs.directories || matrix.specs.group}}/**/${{matrix.specs.pattern}}"
      want-pdf: "${{ !!matrix.specs.want_pdf }}"
    secrets: inherit

  cucumber:
    uses: ./.github/workflows/testing.yml
    with:
      name: "all"
      test-runner: "cucumber"
      want-pdf: true
    secrets: inherit
