name: Deploy production

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "production"
    secrets: inherit
