---
name: Deploy

on:
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to staging
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "staging"
      db_subnets: "STAGING_BOPS_SUBNETS"
      db_sg: "STAGING_BOPS_SG"
    secrets: inherit
