---
name: Deploy

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to production
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-name: "production"
      db_subnets: "PRODUCTION_BOPS_SUBNETS"
      db_sg: "PRODUCTION_BOPS_SG"
    secrets: inherit
